@startuml

skin rose

' title __Simple__ **communication** example

' Alice -> Bob: Authentication Request
' Bob -> Alice: Authentication Response

' title __Simple__ communication example\non several lines

' Alice -> Bob: Authentication Request
' Bob -> Alice: Authentication Response

title
 <u>Simple</u> communication example
 on <i>several</i> lines and using <font color=red>html</font>
 This is hosted by <img:sourceforge.jpg>
end title

Alice -> Bob: Authentication Request
Bob -> Alice: Authentication Response

@enduml
