@startuml

skin rose

' participant "Famous Bob" as Bob << Generated >>
' participant Alice << (C,#ADD1B2) Testable >>

' Bob->Alice: First message

' skinparam guillemet false
' participant "Famous Bob" as Bob << Generated >>
' participant Alice << (C,#ADD1B2) Testable >>

' Bob->Alice: First message

participant Bob << (C,#ADD1B2) >>
participant Alice << (C,#ADD1B2) >>

Bob->Alice: First message

@enduml
